"""
Script receives:
1) domain.pddl
2) NProbDF - a pandas dataframe that holds paths to N problems and their plans generated from the given domain
3) new_problems_path
The script iterates through the NProbDF dataframe created by the "generate_problem_plans.py" and sends the paths of each
problem and its corresponding plan to the "regenerate_data.py" script that augments data by create all the "mid-way"
problems generated by doing each one of the actions in plan after each plan action generates the problem achieved by
that step. for achieving the goal of problem (assumes plan actions are OK).

Each subproblem created by regenerate data is then added to NProbDF which is then returned to the
"generate_problem_plans.py" script
"""
import regenrate_data
import pandas as pd
import sys

def add_subproblems_to_df(df, subproblem_paths, df_parent_row):
    prob_row = df_parent_row
    df_insert = pd.DataFrame([prob_row]*len(subproblem_paths), columns=df.columns).reset_index(drop=True)
    # stating relation of all subproblems to their parent problem in the dataframe
    df_insert["from_id"] = df_parent_row['id'].iloc[0]
    # stating that all rows that will be added to the df are of subproblems
    df_insert["id"] = "sub-problem"

    for i, subproblem_path in enumerate(subproblem_paths):
        # assigning the subproblem path to each line
        df_insert.iloc[i]["problem.pddl"] = subproblem_paths[i]
        df_insert.iloc[i]["plan length"] = df_parent_row["plan length"] - i - 1

    df = pd.concat([df, df_insert])

    return df
##############################################################################################
def main(domain_file, NProbDF, new_problems_path):
    N = NProbDF.shape[0]
    for i in range(N):
        curr_prob_path = NProbDF.iloc[i]["problem.pddl"].iloc[0]
        curr_plan_path = NProbDF.iloc[i]["plan"].iloc[0]
        curr_prob_id = NProbDF.iloc[i]['id'].iloc[0]
        subproblem_paths = regenrate_data.main(domain_file, curr_prob_path, curr_plan_path, new_problems_path)
        if len(subproblem_paths) == 0:
            continue

        NProbDF = add_subproblems_to_df(NProbDF, subproblem_paths, NProbDF.iloc[i])
    return NProbDF


##############################################################################################
if __name__ == "__main__":

    if len(sys.argv) != 5:
        print("-E- Usage: " + str(sys.argv[0]),
              "<domain pddl file path> <problem pddl file path> <plan for problem path> "
              "<path for for new problems>")
        sys.exit(1)
    N = sys.argv[1]
    domain_file = sys.argv[2]
    NProbDF = sys.argv[3]
    new_problems_path = sys.argv[4]

    main(N, domain_file, NProbDF, new_problems_path)
