# imports
import random
import subprocess
import pandas as pd
import numpy as np
from datetime import datetime
import os
import augment_problem_data
import time
import h_config

config = h_config.config().get_config()


###############################################################################################
def GenerateProblemsPlans(NProbDF):
    """
    Activate external problems generator code and planner code,
    and add both problem and plan to the problem data frame given
    :param NProbDF: data frame with all the data for each problem generation
    :return: the data frame given with added data about problem in pddl
            and the plan for problem (if exists)
    """
    config = h_config.config.get_config()
    processes = []
    # create problem using the parameters in data frame
    for i in range(0, NProbDF.shape[0]):
        NProbDF.at[i, "id"] = i
        NProbDF.at[i, "from_id"] = i
        gen_val_list = NProbDF.iloc[i].to_list()[:-4]
        cmd_val_list = [np.array2string(val) for val in gen_val_list]
        cmd_val_list.insert(0, config.generator_path)
        cmd_line = " ".join(cmd_val_list)
        prob_out_path = os.path.join(config.problems_dir, "prob_" + i.__str__() + ".pddl")
        with open(prob_out_path, "w") as fd:
            ProblemDescription = subprocess.Popen(cmd_line, stdout=fd, stderr=subprocess.PIPE, shell=True)
            processes.append(ProblemDescription)
        NProbDF.at[i, "problem"] = prob_out_path

    for process in processes:
        process.wait()

    processes = []
    # for each problem, create plan using planner
    for i in range(0, NProbDF.shape[0]):
        plan_out_path = os.path.join(config.plans_dir, "plan_" + i.__str__())
        cmd_line_args = ['python', config.planner_path, "--plan-file", plan_out_path, config.domain_pddl_path,
                         NProbDF.at[i, "problem"], config.planner_search_flag]
        cmd_line = " ".join(cmd_line_args)
        sub_res = subprocess.Popen(cmd_line, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
        processes.append(sub_res)

        # check if plan was found

        NProbDF.at[i, "plan"] = plan_out_path

    for process in processes:
        process.wait()


###############################################################################################
def GenProblemsDataFrame():
    """
    Function Description: Generates N problems of a certain domain using a given generator path and a list of its
                     needed descriptor titles and their ranges

    Output: 1- NProbDF (Pandas DataFrame) - The columns of the dataframe are the problem descriptors and the
           and the final column is the problem as generated,and each row represents a problem generated
    """

    DescriptorTitles = []
    for i in range(len(config.ProbDescriptorsInfo)):
        DescriptorTitles.append(config.ProbDescriptorsInfo[i][0])
    DescriptorTitles.append("problem")
    DescriptorTitles.append("plan")
    DescriptorTitles.append("id")
    DescriptorTitles.append("from_id")
    list_generated_descriptor = []
    for i in range(config.N):
        ProbDescriptorVals = []
        for j in range(len(config.ProbDescriptorsInfo)):
            descr_value = random.randint(config.ProbDescriptorsInfo[j][1], config.ProbDescriptorsInfo[j][2])
            ProbDescriptorVals.append(descr_value)
            if j == (len(config.ProbDescriptorsInfo) - 1):
                ProbDescriptorVals += ["", "", i, "parent_problem"]
                list_generated_descriptor.append(ProbDescriptorVals)

    NProbDF = pd.DataFrame(list_generated_descriptor, columns=DescriptorTitles)
    GenerateProblemsPlans(NProbDF)
    return NProbDF


##############################################################################################
def ExtractPlan(NProbDF):
    """
    Extracts the plan itself from all the plan data that is created by planner
    and overrides the original plan generated by planner
    """
    import re
    time.sleep(1)
    plan_lengths = []
    correct_plans = []
    for index, row in NProbDF.iterrows():
        needed_data = []
        curr_plan_path = row["plan"]
        plan_exist = False

        if not os.path.exists(curr_plan_path):
            print("no plan for: " + str(index))
            continue

        with open(curr_plan_path, 'r') as plan_f:
            for cnt, line in enumerate(plan_f):
                if re.search("cost = ", line, re.IGNORECASE):
                    plan_length = re.findall("[0-9]+", line)
                    plan_lengths.append(plan_length[0])
                    plan_exist = True
                    break

                needed_data.append(line)

        if plan_exist:
            correct_plans.append(index)
            with open(curr_plan_path, "w") as fh:
                for plan_step in needed_data:
                    fh.write(plan_step)

    corrupt_plans = [i for i in range(config.N)]
    for correct_plan in correct_plans:
        corrupt_plans.remove(correct_plan)

    NProbDF = NProbDF.drop(corrupt_plans)
    NProbDF["plan length"] = plan_lengths

    return NProbDF

##############################################################################################
def create_problem_images(df):
    processes = []
    df['image'] = None
    for i in range(0, df.shape[0]):

        image_path = os.path.join(config.img_dir, "prob_img_" + str(i) + ".png")
        cmd_line_args = ['python', config.image_creater_path, "--image-from-lifted-task ",
                         config.domain_pddl_path, df.at[i, "problem"], image_path]
        cmd_line = " ".join(cmd_line_args)
        ProblemDescription = subprocess.Popen(cmd_line, shell=True)
        processes.append(ProblemDescription)
        df.at[i, "image"] = image_path

    for process in processes:
        process.wait()
    

##############################################################################################
def add_date_to_paths(config):
    """
    adds time and date signature to directories names
    """
    # datetime object containing current date and time
    now = datetime.now()

    # dd/mm/YY H:M:S
    dt_string = now.strftime("_%d_%m_%Y_%H_%M_%S")
    config.problems_dir += dt_string
    config.subproblems_dir += dt_string
    config.plans_dir += dt_string
    config.img_dir += dt_string
    config.csv_path += dt_string + ".csv"


###############################################################################################
def create_dirs(paths_list):
    for path in paths_list:
        try:
            os.mkdir(path)
        except OSError:
            print("Creation of the directory %s failed" % path)
            exit(1)
###############################################################################################
def save_info_df_as_csv(info_df):
    info_df.to_csv(config.csv_path)

##############################################################################################
def main():
    add_date_to_paths(config)
    create_dirs([config.plans_dir, config.problems_dir, config.subproblems_dir, config.img_dir])
    NProbDF = GenProblemsDataFrame()
    NProbDF = ExtractPlan(NProbDF)
    NProbDF = augment_problem_data.main(config.domain_pddl_path, NProbDF, config.subproblems_dir)
    create_problem_images(NProbDF)
    save_info_df_as_csv(NProbDF)
    return NProbDF


if __name__ == '__main__':
    main()
